title: Benjamin Ramsey # your name (or website title) here
logo: "/images/IMG_0577.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am a Senior at Michigan State University studying Data Science. 
  Upon graduation, I would like work within the healthcare domain to enhance 
  the efficiency of healthcare providers and insurers.
  <br><br>
  I am currently a Undergraduate Learning Assistant for a Computer Science course with an
  emphasis on Python and Algorithmic Thinking.
  I have previously interned with Delta Dental of Michigan and Roosevelt Innovations. 
  <br><br>
  <a href="https://www.linkedin.com/in/ben-ramsey-msu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
