title: Benjamin Ramsey # your name (or website title) here
logo: "/images/IMG_0577.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am a junior at Michigan State University studying Data Science. 
  Upon graduation, I would like work within the healthcare domain to enhance 
  the efficiency of healthcare providers and insurers.
  <br><br>
  I am currently interning with Roosevelt Innovations, a partner company of Delta Dental, 
  to deliver innovative insurance solutions across 14 states. In addition to this, I am an
  Undergraduate Teaching Assistant for the Computer Science department at Michigan State.
  <br><br>
  <a href="https://www.linkedin.com/in/ben-ramsey-msu/">View My LinkedIn Profile</a> 
  
# theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
